# Generated by Django 3.2.2 on 2021-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_fcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_link', models.URLField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token1', models.CharField(max_length=1500)),
                ('token2', models.CharField(max_length=1500)),
                ('token3', models.CharField(max_length=1500)),
            ],
        ),
    ]
