# Generated by Django 3.2.2 on 2021-11-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_auto_20210626_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceresponse',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='batch',
        ),
    ]
